# Logging Configuration for DP100 Monitor

version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
  
  detailed:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(funcName)s:%(lineno)d - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout

  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: logs/dp100-monitor.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8

  error_file:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: detailed
    filename: logs/dp100-monitor-error.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8

loggers:
  dp100_monitor:
    level: DEBUG
    handlers: [console, file, error_file]
    propagate: false
  
  dp100_monitor.device:
    level: DEBUG
    handlers: [console, file, error_file]
    propagate: false
  
  dp100_monitor.gui:
    level: INFO
    handlers: [console, file]
    propagate: false
  
  dp100_monitor.storage:
    level: DEBUG
    handlers: [console, file, error_file]
    propagate: false

root:
  level: WARNING
  handlers: [console]